[paths]
# Output directory
out_dir = 'separation_results'

# Vocal model: BS Roformer (viperx edition)
[vocal_model]
type = 'bs_roformer'
config = '$msst/configs/viperx/model_bs_roformer_ep_317_sdr_12.9755.yaml'
checkpoint = '$msst/results/model_bs_roformer_ep_317_sdr_12.9755.ckpt'

# Single stem model: BS Roformer (viperx edition)
[other_model]
type = 'bs_roformer'
config = '$msst/configs/viperx/model_bs_roformer_ep_937_sdr_10.5309.yaml'
checkpoint = '$msst/results/model_bs_roformer_ep_937_sdr_10.5309.ckpt'

# Single stem model: HTDemucs4 FT Drums
[drums_model]
type = 'htdemucs'
config = '$msst/configs/config_musdb18_htdemucs.yaml'
checkpoint = '$msst/results/f7e0c4bc-ba3fe64a.th'

# Single stem model: HTDemucs4 FT Bass
[bass_model]
type = 'htdemucs'
config = '$msst/configs/config_musdb18_htdemucs.yaml'
checkpoint = '$msst/results/d12395a8-e57c48e6.th'

# Single stem model: MelBand Roformer (anvuew edition)
[[extra_models]]
key = 'dereverb'
type = 'mel_band_roformer'
config = '$msst/results/dereverb_mel_band_roformer_anvuew.yaml'
checkpoint = '$msst/results/dereverb_mel_band_roformer_anvuew_sdr_19.1729.ckpt'
